
project_id = "xugrsxymeyrfyqdeirjc"

[api]
# Requests per second threshold above which an alert is triggered
realtime_requests_per_second_alert = 20
# Requests per second threshold above which rate limiting is triggered
realtime_requests_per_second_limit = 100

[api.endpoint]
# Set the expiration for Supabase URL
default_aud = "authenticated"

[db]
# Port to use for the local DB URL
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions]
[functions.create-checkout]
verify_jwt = true
[functions.check-subscription]
verify_jwt = true
[functions.customer-portal]
verify_jwt = true
[functions.pause-subscription]
verify_jwt = true
